name: Unzip Project
on:
  push:
    paths:
      - 'tip-splitter.zip'

jobs:
  unzip:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Unzip file
        run: |
          unzip -o archive.zip -d ./
          rm archive.zip

      - name: Commit changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add .
          git commit -m "Unzipped project files automatically" || exit 0
          git push
          
